services:
  postgres:
    image: postgres:16-alpine
    container_name: octor-postgres
    environment:
      - POSTGRES_USER=octor
      - POSTGRES_PASSWORD=octor
      - POSTGRES_DB=octor
    ports:
      - "5433:5432"
    volumes:
      - ./infra-data/postgres:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:7-alpine
    container_name: octor-redis
    ports:
      - "6380:6379"
    volumes:
      - ./infra-data/redis:/data

  nats:
    image: nats:2-alpine
    container_name: octor-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -js

