CREATE DATABASE url_store;
CREATE DATABASE abuse_store;
CREATE DATABASE claims_provider;
CREATE DATABASE vault;
GRANT ALL PRIVILEGES ON DATABASE url_store TO octor;
GRANT ALL PRIVILEGES ON DATABASE abuse_store TO octor;
GRANT ALL PRIVILEGES ON DATABASE claims_provider TO octor;
GRANT ALL PRIVILEGES ON DATABASE vault TO octor;
