#!/usr/bin/env bash
# ==============================================================================
# OCTOR ARR STACK AUTOMATED WIRING SCRIPT (octor-arr-wire.sh)
# ==============================================================================
# Sets up, runs, and wires Prowlarr, Radarr, Sonarr, and Whisparr automatically.
# ==============================================================================

set -euo pipefail

# --- Configuration & Paths ---
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$PROJECT_ROOT/custom.env"
ARR_DIR="$(cd "$PROJECT_ROOT/.." && pwd)/Big ARRS"

echo "=== OCTOR *ARR WIRING & INDEXER BOOTSTRAPPING ==="

if [[ ! -f "$ENV_FILE" ]]; then
    echo "❌ Error: $ENV_FILE not found!"
    exit 1
fi

# Load env variables
export $(grep -v '^#' "$ENV_FILE" | xargs)

# 1. Setup target directory and copy docker-compose template from reference
echo "Preparing Big ARRS folder..."
mkdir -p "$ARR_DIR/config/prowlarr" "$ARR_DIR/config/radarr" "$ARR_DIR/config/sonarr" "$ARR_DIR/config/whisparr" "$ARR_DIR/data" "$ARR_DIR/downloads"

# Copy compose/endpoints templates from reference if they don't exist
if [ ! -f "$ARR_DIR/docker-compose.yml" ]; then
    echo "Copying Big ARRS docker templates from local repository..."
    cp "$PROJECT_ROOT/arr-templates/docker-compose.yml" "$ARR_DIR/docker-compose.yml"
    cp "$PROJECT_ROOT/arr-templates/endpoints.py" "$ARR_DIR/endpoints.py"
fi

# Start Arr stack
echo "Starting Arr container stack..."
cd "$ARR_DIR"
sudo PUID=$(id -u) PGID=$(id -g) docker compose up -d

# Wait for configuration XMLs to be generated by the container runtimes
echo "Waiting for container configurations to boot..."
sleep 15

# Update URL base in configurations to match Nginx/Octor path routing
update_xml_urlbase() {
    local xml_file="$1"
    local base_path="$2"
    if [ -f "$xml_file" ]; then
        echo "Setting URL Base to '$base_path' in $(basename $(dirname "$xml_file"))..."
        sed -i "s|<UrlBase>.*</UrlBase>|<UrlBase>$base_path</UrlBase>|g" "$xml_file"
    fi
}

update_xml_urlbase "$ARR_DIR/config/prowlarr/config.xml" "/prowlarr"
update_xml_urlbase "$ARR_DIR/config/radarr/config.xml" "/radarr"
update_xml_urlbase "$ARR_DIR/config/sonarr/config.xml" "/sonarr"
update_xml_urlbase "$ARR_DIR/config/whisparr/config.xml" "/whisparr"

echo "Restarting Arr stack to apply URL bases..."
sudo PUID=$(id -u) PGID=$(id -g) docker compose restart
sleep 5

parse_api_key() {
    local xml_file="$1"
    local app_name="$2"
    local elapsed=0
    echo -n "Waiting for $app_name API Key..." >&2
    while [ $elapsed -lt 40 ]; do
        if [ -f "$xml_file" ] && grep -q "<ApiKey>" "$xml_file"; then
            local key=$(sed -n 's|.*<ApiKey>\(.*\)</ApiKey>.*|\1|p' "$xml_file" | tr -d '\r')
            echo " ✓ ($key)" >&2
            echo "$key"
            return 0
        fi
        printf "." >&2
        sleep 2
        elapsed=$((elapsed + 2))
    done
    echo " ❌" >&2
    echo "" >&2
    return 1
}

wait_for_api() {
    local port="$1"
    local app_name="$2"
    local key="$3"
    local elapsed=0
    echo -n "Waiting for $app_name API on port $port to be ready..." >&2
    while [ $elapsed -lt 60 ]; do
        local resp=""
        resp=$(curl -sf "http://localhost:$port/$app_name/api/v3/system/status" -H "X-Api-Key: $key" 2>/dev/null) || \
        resp=$(curl -sf "http://localhost:$port/$app_name/api/v1/system/status" -H "X-Api-Key: $key" 2>/dev/null) || true
        
        if echo "$resp" | grep -q '"version"'; then
            echo " ✓" >&2
            return 0
        fi
        printf "." >&2
        sleep 2
        elapsed=$((elapsed + 2))
    done
    echo " ❌ (Timeout)" >&2
    return 1
}

PROWLARR_KEY=$(parse_api_key "$ARR_DIR/config/prowlarr/config.xml" "Prowlarr") || PROWLARR_KEY=""
RADARR_KEY=$(parse_api_key "$ARR_DIR/config/radarr/config.xml" "Radarr") || RADARR_KEY=""
SONARR_KEY=$(parse_api_key "$ARR_DIR/config/sonarr/config.xml" "Sonarr") || SONARR_KEY=""
WHISPARR_KEY=$(parse_api_key "$ARR_DIR/config/whisparr/config.xml" "Whisparr") || WHISPARR_KEY=""

# Update custom.env with the parsed API keys
echo "Updating custom.env with active API keys..."
if [ -n "$PROWLARR_KEY" ]; then
    sed -i "s|^PROWLARR_API_KEY=.*|PROWLARR_API_KEY=$PROWLARR_KEY|" "$ENV_FILE"
fi
if [ -n "$RADARR_KEY" ]; then
    sed -i "s|^RADARR_API_KEY=.*|RADARR_API_KEY=$RADARR_KEY|" "$ENV_FILE"
fi
if [ -n "$SONARR_KEY" ]; then
    sed -i "s|^SONARR_API_KEY=.*|SONARR_API_KEY=$SONARR_KEY|" "$ENV_FILE"
fi
if [ -n "$WHISPARR_KEY" ]; then
    sed -i "s|^WHISPARR_API_KEY=.*|WHISPARR_API_KEY=$WHISPARR_KEY|" "$ENV_FILE"
fi

# Reload environment
export $(grep -v '^#' "$ENV_FILE" | xargs)

# 2. Bootstrapping Indexers in Prowlarr
if [ -n "$PROWLARR_KEY" ]; then
    wait_for_api 9696 "prowlarr" "$PROWLARR_KEY" || exit 1
    echo "Bootstrapping indexers in Prowlarr..."
    
    # 1. The Pirate Bay
    echo "  -> Adding The Pirate Bay..."
    curl -sf -X POST "http://localhost:9696/prowlarr/api/v1/indexer" \
        -H "X-Api-Key: $PROWLARR_KEY" \
        -H "Content-Type: application/json" \
        -d '{
            "name": "The Pirate Bay",
            "enable": true,
            "protocol": "torrent",
            "priority": 25,
            "implementation": "Cardigann",
            "configContract": "CardigannSettings",
            "appProfileId": 1,
            "fields": [
                {"name": "definitionFile", "value": "thepiratebay"},
                {"name": "extraFieldData", "value": "{\"apiurl\":\"apibay.org\",\"uploader\":\"\"}"},
                {"name": "baseSettings.limitsUnit", "value": 0},
                {"name": "torrentBaseSettings.preferMagnetUrl", "value": true}
            ]
        }' >/dev/null || echo "⚠️  Failed to register TPB in Prowlarr."

    # 2. Knaben
    echo "  -> Adding Knaben..."
    curl -sf -X POST "http://localhost:9696/prowlarr/api/v1/indexer" \
        -H "X-Api-Key: $PROWLARR_KEY" \
        -H "Content-Type: application/json" \
        -d '{
            "name": "Knaben",
            "enable": true,
            "protocol": "torrent",
            "priority": 25,
            "implementation": "Knaben",
            "configContract": "NoAuthTorrentBaseSettings",
            "appProfileId": 1,
            "fields": [
                {"name": "baseSettings.limitsUnit", "value": 0},
                {"name": "torrentBaseSettings.preferMagnetUrl", "value": true}
            ]
        }' >/dev/null || echo "⚠️  Failed to register Knaben in Prowlarr."

    # 3. RuTracker (if credentials provided)
    if [ -n "${RUTRACKER_USER:-}" ] && [ -n "${RUTRACKER_PASS:-}" ]; then
        echo "  -> Adding RuTracker..."
        curl -sf -X POST "http://localhost:9696/prowlarr/api/v1/indexer" \
            -H "X-Api-Key: $PROWLARR_KEY" \
            -H "Content-Type: application/json" \
            -d "{
                \"name\": \"RuTracker.org\",
                \"enable\": true,
                \"protocol\": \"torrent\",
                \"priority\": 25,
                \"implementation\": \"RuTracker\",
                \"configContract\": \"RuTrackerSettings\",
                \"appProfileId\": 1,
                \"fields\": [
                    {\"name\": \"russianLetters\", \"value\": true},
                    {\"name\": \"useMagnetLinks\", \"value\": true},
                    {\"name\": \"username\", \"value\": \"$RUTRACKER_USER\"},
                    {\"name\": \"password\", \"value\": \"$RUTRACKER_PASS\"},
                    {\"name\": \"baseUrl\", \"value\": \"https://rutracker.net/\"},
                    {\"name\": \"baseSettings.limitsUnit\", \"value\": 0},
                    {\"name\": \"torrentBaseSettings.preferMagnetUrl\", \"value\": false}
                ]
            }" >/dev/null || echo "⚠️  Failed to register RuTracker in Prowlarr."
    fi
fi

# 3. Wiring Octor as Transmission Download Client (Optional/Interactive)
# Split emails to pick first admin user
ADMIN_USER=$(echo "$ADMIN_EMAILS" | cut -d, -f1)

wire_download_client() {
    local port="$1"
    local key="$2"
    local app_name="$3"
    local category="$4"
    
    wait_for_api "$port" "$app_name" "$key" || return 1
    echo "Wiring Octor Transmission client in $app_name..."
    curl -sf -X POST "http://localhost:$port/$app_name/api/v3/downloadclient" \
        -H "X-Api-Key: $key" \
        -H "Content-Type: application/json" \
        -d "{
            \"name\": \"Octor Transmission\",
            \"enable\": true,
            \"implementation\": \"Transmission\",
            \"configContract\": \"TransmissionSettings\",
            \"priority\": 1,
            \"fields\": [
                {\"name\": \"host\", \"value\": \"host.docker.internal\"},
                {\"name\": \"port\", \"value\": 8080},
                {\"name\": \"useSsl\", \"value\": false},
                {\"name\": \"urlBase\", \"value\": \"/transmission/\"},
                {\"name\": \"username\", \"value\": \"$ADMIN_USER\"},
                {\"name\": \"password\", \"value\": \"$AUTOMATION_API_KEY\"},
                {\"name\": \"movieCategory\", \"value\": \"$category\"},
                {\"name\": \"tvCategory\", \"value\": \"$category\"},
                {\"name\": \"recentMoviePriority\", \"value\": 0},
                {\"name\": \"olderMoviePriority\", \"value\": 0},
                {\"name\": \"addPaused\", \"value\": false}
            ]
        }" >/dev/null && echo "✓ Wired $app_name successfully." || echo "⚠️  Failed to wire $app_name."
}

# Prompt Sonarr
if [ -n "$SONARR_KEY" ]; then
    read -p "Configure Octor in Sonarr? (y/n) [y]: " RUN_SONARR
    RUN_SONARR=${RUN_SONARR:-y}
    if [[ "$RUN_SONARR" =~ ^[yY]$ ]]; then
        wire_download_client 8989 "$SONARR_KEY" "sonarr" "tv-sonarr"
    fi
fi

# Prompt Radarr
if [ -n "$RADARR_KEY" ]; then
    read -p "Configure Octor in Radarr? (y/n) [y]: " RUN_RADARR
    RUN_RADARR=${RUN_RADARR:-y}
    if [[ "$RUN_RADARR" =~ ^[yY]$ ]]; then
        wire_download_client 7878 "$RADARR_KEY" "radarr" "movies-radarr"
    fi
fi

# Prompt Whisparr
if [ -n "$WHISPARR_KEY" ]; then
    read -p "Configure Octor in Whisparr? (y/n) [y]: " RUN_WHISPARR
    RUN_WHISPARR=${RUN_WHISPARR:-y}
    if [[ "$RUN_WHISPARR" =~ ^[yY]$ ]]; then
        wire_download_client 6969 "$WHISPARR_KEY" "whisparr" "adult-whisparr"
    fi
fi

echo "=== ARR STACK WIRING AND INTEGRATION COMPLETE ==="
